data:
  domain: [-3.1415, 3.1415] # domain of x values
  omegas: 4
  amplitude: 0.5

model:
  n_qubits: 5
  n_layers: 5
  circuit_type: "Circuit_19" # Circuit_1, Circuit_5, Circuit_9, Circuit_15, Circuit_18, Circuit_19, Hardware_Efficient, Strongly_Entangling, No_Entangling
  data_reupload: True
  output_qubit: -1
  initialization: "zero-controlled" # random, zero, zero-controlled, pi-controlled
  initialization_domain: [0, 6.283185307179586]
  shots: -1 # number or -1 if expectation value should be used
  noise_params:
    BitFlip: 0.06
    PhaseFlip: 0.06
    AmplitudeDamping: 0.06
    PhaseDamping: 0.06
    Depolarizing: 0.06
  noise_steps: 6

seed: 1000

entanglement:
  # Entanglement Params
  n_samples: 10

expressibility:
  # Expressibility Params
  n_samples: 3
  n_input_samples: 0
  n_bins: 75

coefficients:
  # Coefficients Params
  n_samples: 3

training:
  steps: 1000
  learning_rate: 0.01
  batch_size: -1
  log_entangling: False
  convergence:
    threshold: 5e-4 # threshold for the cost, -1 to disable
    gradient: -1 # threshold for the cost gradient, -1 to disable
    steps: 50 # gradient is checked for the last n steps (mavg)
