domain: [-0.7,0.7] # domain of x values
omegas: [1.0,2.0,3.0,4.0]
coefficients: [1.0,1.0,1.0,1.0]

n_qubits: 3
n_layers: 3
circuit_type: 'Circuit_19' # Circuit_1, Circuit_5, Circuit_9, Circuit_15, Circuit_18, Circuit_19, Hardware_Efficient, Strongly_Entangling, No_Entangling
data_reupload: True
output_qubit: 0
samples: 100
seed: 1000

noise_params:
  BitFlip: 0.0
  PhaseFlip: 0.0
  AmplitudeDamping: 0.0
  PhaseDamping: 0.0
  Depolarizing: 0.0

epochs: 10
learning_rate: 0.001
batch_size: -1