domain: [-0.7,0.7] # domain of x values
# Up to 3 dim allowed but each dimension must have the same length.
# Different lenghts are supported by using '0's as placeholder
omega: [[1.0,2.0,3.0,4.0], [1.0,2.0,3.0,0.0], [1.0,2.0,0.0,0.0]] 