domain: [-0.7,0.7] # domain of x values
omegas: [1.0,2.0,3.0,4.0]
coefficients: [1.0,1.0,1.0,1.0]

n_qubits: 3
n_layers: 3
circuit_type: 'circuit19'
data_reupload: True
samples: 100
seed: 1000

epochs: 100
learning_rate: 0.001
batch_size: -1