data:
  domain: [-3.1415, 3.1415] # domain of x values
  omegas: 5
  amplitude: 0.5

model:
  n_qubits: 5
  n_layers: 1
  circuit_type: "Circuit_15" # Circuit_1, Circuit_5, Circuit_9, Circuit_15, Circuit_18, Circuit_19, Hardware_Efficient, Strongly_Entangling, No_Entangling, Strongly_Entangling_Plus
  data_reupload: True
  output_qubit: -1
  initialization: "random" # random, zero, zero-controlled, pi-controlled
  initialization_domain: [0, 6.283185307179586]
  shots: -1 # number or -1 if expectation value should be used
  encoding: ["RX", "RY"]
  noise_params:
    GateError: 0.0
    BitFlip: 0.0
    PhaseFlip: 0.0
    AmplitudeDamping: 0.0
    PhaseDamping: 0.0
    Depolarizing: 0.0
    MultiQubitDepolarizing: 0.0
    StatePreparation: 0.0
    Measurement: 0.0
    ThermalRelaxation:
      0.0
      # T1: 18000.0
      # T2: 10000.0
      # t_factor: 5
  noise_steps: 6
  mp_threshold: 1000

seed: 1000

entanglement:
  # Entanglement Params
  measure: "EF" # Entanglement of Formation (EF), Meyer-Wallach (MW), Relative Entropy of Entanglement (RE)
  n_samples: 250
  n_sigmas: 5 # Only applies when entanlement.measure = "RE"
  scale: True

expressibility:
  # Expressibility Params
  n_samples: 250
  n_input_samples: 0
  n_bins: 75

coefficients:
  # Coefficients Params
  n_samples: 250
  zero_coefficient: True
  oversampling: 1
  selective_noise: "both" # "both", "iec", "pqc" (where to apply noise)
  scale: True

training:
  steps: 1000
  learning_rate: 0.01
  batch_size: -1
  convergence:
    threshold: 5e-4 # threshold for the cost, -1 to disable
    gradient: -1 # threshold for the cost gradient, -1 to disable
    steps: 50 # gradient is checked for the last n steps (mavg)
